application: bx90210
version: 1c3
runtime: python
api_version: 1

handlers:
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

- url: /robots.txt
  static_files: static/robots.txt
  upload: static/robots.txt

- url: /remote_api
  script: $PYTHON_LIB/google/appengine/ext/remote_api/handler.py
  login: admin

- url: /cron
  script: b90210.py
  login: admin

- url: /delete
  script: b90210.py
  login: admin

- url: .*
  script: b90210.py
  


